# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=None, max_length=225)),
                ('Main_img', models.CharField(default=None, max_length=225)),
                ('Post_content', models.TextField(default=None)),
                ('Post_date', models.DateTimeField(verbose_name='date published')),
                ('Post_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Auto', max_length=225)),
                ('Profile_score', models.IntegerField(default=0)),
                ('Post_number', models.IntegerField(default=0)),
                ('profile_img', models.ImageField(default='No_img', upload_to='')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
                ('Tag_postnum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='main_post',
            name='Profile_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
        migrations.AddField(
            model_name='main_post',
            name='Tag',
            field=models.ManyToManyField(default=None, to='home.Tag_list'),
        ),
    ]
