# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_main_post_post_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_post',
            name='Post_short',
            field=models.TextField(default='this is ta text'),
        ),
    ]
