# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161109_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=80)),
                ('Email', models.CharField(default=None, max_length=80)),
                ('Website', models.CharField(default=None, max_length=80)),
                ('Subscribe', models.IntegerField(default=0)),
                ('body', models.TextField(default=None)),
                ('Post_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.Main_post')),
            ],
        ),
    ]
