# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='Post_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='Comment_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.Comments'),
        ),
    ]
