# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161109_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Comment_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='reply',
            name='Reply_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
